'use client'
import type { Metadata } from 'next'
import './globals.css'
import { Inter } from 'next/font/google'
// import Link  from 'next/link';
import Link from 'react-dom';


const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Portfólio',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
